# Generated by Django 2.0.7 on 2019-10-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=15)),
                ('password', models.TextField(max_length=30)),
                ('name', models.TextField(max_length=100)),
            ],
        ),
    ]
